# This file was generated by GoReleaser. DO NOT EDIT.
cask "cchef" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "4d849d2e61caac776779f6d3c925cbef37f3c90ffff5cc32cd53673496f7773e"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fa75398c441852d3460cc5d6aaad6711764837d38e20fd48e3a80b8be9cf038"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99aa8105e43b9148bfae5857f0eaf4b242f651e3cdc4516c1c55555147e68f16"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be860e10c7548acc899566dc861ae27ec1d3f4b0bbf7e2686983dbc5fdcbabbf"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cchef"
  desc "CyberChef on the command line"
  homepage "https://github.com/roberson-io/cchef"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cchef"
  manpage "man/cchef.1"
  bash_completion "completions/cchef.bash"
  fish_completion "completions/cchef.fish"
  zsh_completion "completions/_cchef"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cchef")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cchef"]
    end
  end

  # No zap stanza required

end
