# This file was generated by GoReleaser. DO NOT EDIT.
cask "cchef" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "3e34970dd9bac249a4cd35104222ea85be4af0089aca1331ed6d86336d05ae24"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "898d8c0c3cde8ebed09df10fae9ea84abdb095287fd58423838525eeeb49f65f"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61e1db8b90bf32b5482de997de69976d87b688baa900b3f4a8db7c60ec9c7fcd"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78ddd0f9c18ccfd9ef857e7a9799c84e37f2319d103436662188b59e59cecfd3"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cchef"
  desc "CyberChef on the command line"
  homepage "https://github.com/roberson-io/cchef"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cchef"
  manpage "man/cchef.1"
  bash_completion "completions/cchef.bash"
  fish_completion "completions/cchef.fish"
  zsh_completion "completions/_cchef"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cchef")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cchef"]
    end
  end

  # No zap stanza required

end
