# This file was generated by GoReleaser. DO NOT EDIT.
cask "cchef" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "bbbad1fd67686a50cfc0a044db4cb9e64fc209e36dcb6a46961d35dbedca3d31"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0e58e3bd2a04ef7b1afd14800082f7c4d207fb75e57feed4364fc8ae0a95802"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25b61bcd77d6033799f268fea4cea5392b2dc3274bc3ceffbae077a46438a874"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e50a6eda834a027c9f3dde37da0b5fb0668dd357a8aa571968da8c7e0e9f521f"
      url "https://github.com/roberson-io/cchef/releases/download/v#{version}/cchef_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cchef"
  desc "CyberChef on the command line"
  homepage "https://github.com/roberson-io/cchef"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cchef"
  manpage "man/cchef.1"
  bash_completion "completions/cchef.bash"
  fish_completion "completions/cchef.fish"
  zsh_completion "completions/_cchef"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cchef")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cchef"]
    end
  end

  # No zap stanza required

end
